# Generated by Django 4.0.6 on 2023-03-02 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30, verbose_name='クラス名')),
                ('weekday', models.CharField(max_length=3, verbose_name='曜日')),
                ('start_time', models.CharField(max_length=30, verbose_name='時間')),
                ('genre', models.CharField(max_length=30, verbose_name='ジャンル')),
                ('inst', models.CharField(max_length=30, verbose_name='インストラクター')),
                ('playce', models.CharField(max_length=30, verbose_name='場所')),
            ],
            options={
                'verbose_name': 'クラス情報',
                'verbose_name_plural': 'クラス情報',
            },
        ),
        migrations.CreateModel(
            name='Event_Apply_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30, unique=True, verbose_name='イベント名')),
                ('place', models.CharField(max_length=30, verbose_name='会場')),
                ('addres', models.CharField(max_length=30, verbose_name='住所')),
                ('start_time', models.IntegerField(verbose_name='開演')),
                ('tickt_info', models.IntegerField(verbose_name='チケット')),
                ('entry_fee', models.IntegerField(verbose_name='参加費')),
                ('date_time', models.DateField(verbose_name='日時')),
            ],
            options={
                'verbose_name': 'イベント申し込み',
                'verbose_name_plural': 'イベント申し込み',
            },
        ),
        migrations.CreateModel(
            name='general_contact_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日付')),
                ('first_name', models.CharField(max_length=30, verbose_name='姓')),
                ('last_name', models.CharField(max_length=30, verbose_name='名')),
                ('telphone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='電話番号')),
                ('mail_address', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('context', models.CharField(max_length=300, verbose_name='内容')),
            ],
            options={
                'verbose_name': '一般の問い合わせ一覧',
                'verbose_name_plural': '一般の問い合わせ一覧',
            },
        ),
        migrations.CreateModel(
            name='lesson_contact_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日付')),
                ('first_name', models.CharField(max_length=30, verbose_name='姓')),
                ('last_name', models.CharField(max_length=30, verbose_name='名')),
                ('gender', models.CharField(choices=[('Man', '男'), ('Women', '女'), ('Not specified', '指定しない')], max_length=20, verbose_name='性別')),
                ('experience_class', models.CharField(choices=[('キッズクラス', 'キッズクラス'), ('OPENクラス', 'OPENクラス'), ('初級クラス', '初級クラス')], max_length=20, verbose_name='体験希望クラス')),
                ('experience_date', models.DateField(verbose_name='希望体験日')),
                ('telphone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='電話番号')),
                ('mail_address', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('context', models.CharField(max_length=300, verbose_name='備考')),
            ],
            options={
                'verbose_name': 'レッスンの問い合わせ一覧',
                'verbose_name_plural': 'レッスンの問い合わせ一覧',
            },
        ),
    ]
