# Generated by Django 4.0.6 on 2023-03-02 06:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='メールアドレス')),
                ('first_name', models.CharField(max_length=10, verbose_name='姓')),
                ('last_name', models.CharField(max_length=10, verbose_name='名')),
                ('first_kana', models.CharField(max_length=10, verbose_name='セイ')),
                ('last_kana', models.CharField(max_length=10, verbose_name='メイ')),
                ('number_of_student', models.IntegerField(null=True, verbose_name='生徒数')),
                ('is_movie_subscription', models.BooleanField(default=False, verbose_name='動画登録')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '親ユーザー一覧',
                'verbose_name_plural': '親ユーザー一覧',
            },
        ),
        migrations.CreateModel(
            name='PerformanceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_name', models.CharField(max_length=32, verbose_name='作品名')),
                ('rehearsal_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='リハーサル時間')),
            ],
            options={
                'verbose_name': '作品申し込み詳細',
                'verbose_name_plural': '作品申し込み詳細',
            },
        ),
        migrations.CreateModel(
            name='UserStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=10, verbose_name='姓')),
                ('last_name', models.CharField(max_length=10, verbose_name='名')),
                ('first_kana', models.CharField(max_length=10, verbose_name='セイ')),
                ('last_kana', models.CharField(max_length=10, verbose_name='メイ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '生徒一覧',
                'verbose_name_plural': '生徒一覧',
            },
        ),
    ]
